# Site settings
title: Clontz.org
header-img: img/home-bg.jpg
email: steven.clontz@gmail.com
description: "Mathematician, Professor, Programmer, and Puzzler"
baseurl: ""
url: "http://www.clontz.org"
twitter_username: StevenXClontz
github_username:  StevenClontz
facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
