# Site settings
title: Steven Clontz
short-title: Clontz.org
header-img: "img/home-bg.jpg"
email: steven.clontz@gmail.com
description: "mathematician, professor, puzzler"
baseurl: ""
url: "http://clontz.org"
twitter_username: StevenXClontz
github_username:  StevenClontz
facebook_username:
mastodon_username: StevenXClontz
mastodon_server: mathstodon.xyz
bluesky_username: StevenXClontz
bluesky_domain: bsky.social

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
plugins: [jekyll-paginate]
